### PR TITLE
Set a VARIANT_ID to be consistent with our cloud images

### PR DESCRIPTION
**Pull request by rjschwei**

### CODE REVIEW

**Comment by schaefi** [comment]
Thanks, I wonder why this setting is not part of the installation of the product package ?

I think the patch part of the version information needs to be raised

**Comment by rjschwei** [comment]
Din't bump the version as it is not urgent to get this out, since it is only a consistency change.

**Comment by schaefi** [comment]
> Din't bump the version as it is not urgent to get this out, since it is only a consistency change.

ok

@rjschwei Then I only have one question as the description does not answer it. You are setting VARIANT_ID to the os-release file. There are other components on SLE that adds/manages information on this file. I'd like to understand if this extension is something new we from pubcloud just add or if this is something that can conflict with other parts of SLE ?

Sorry since the systemd config file nightmare I'm cautious on these type of changes.

Thanks

**Comment by schaefi** [comment]
please also remember this is not a classic cloud image. It's sent to Microsoft and they add stuff on top of it. As it basically running SAP HANA workflows and the product information and other data is taken from /etc/os-release I want to be absolutely sure this is not causing trouble

**Review by schaefi — APPROVED** [review]
Thanks for the effort, given I understand the details and there are no bad after effects all this is fine :+1:

**Comment by rjschwei** [comment]
> > Din't bump the version as it is not urgent to get this out, since it is only a consistency change.
> 
> ok
> 
> @rjschwei Then I only have one question as the description does not answer it. You are setting VARIANT_ID to the os-release file. There are other components on SLE that adds/manages information on this file. I'd like to understand if this extension is something new we from pubcloud just add or if this is something that can conflict with other parts of SLE ?
> 
> Sorry since the systemd config file nightmare I'm cautious on these type of changes.
> 
> Thanks

Today non of the SUSE products set VARIANT_ID. When looking at os-release as provided by the distro SLES and SLES For SAP are indistinguishable. This let's us from a cloud perspective distinguish between SLES and SLES For SAP in another way than hunting for the baseproduct link. It also allows us to ensure that baseproduct link and image build setup match. This latter part would also apply to the LI/VLI images for testing. For example

```
if 'sles-sap' in os_release and baseproduct_link != SLES_SAP:
    raise ProductMismatchException()
```

**Comment by rjschwei** [comment]
> please also remember this is not a classic cloud image. It's sent to Microsoft and they add stuff on top of it. As it basically running SAP HANA workflows and the product information and other data is taken from /etc/os-release I want to be absolutely sure this is not causing trouble

Yes, I am taking the different use case into consideration. There is no guarantee that someone claver will not add VARIANT_ID to our default os-release at some point in the future.

**Comment by schaefi** [comment]
ok thanks for clarification

**Pull request merged**
