### PR TITLE
Include salt formula packages etc. in SLES for SAP images

### PR DESCRIPTION
**Pull request by aosthof**
- Requested in jsc#11453 (Deployment of HANA Scale-up Performance Optimized Scenario from Salt (SUMA 4.0)
- Requested in jsc#11454 (Automate setup of DRBD NFS-Share in SALT and Terraform)

### CODE REVIEW

**Comment by schaefi** [comment]
The build in obs will start automatically. I'll watch the results:

```
 Devel:PubCloud:Azure:ImagesSLE15:Large-SP1
  - images               x86_64     SLES15-SP1-SAP-Azure-LI-BYOS:Devel building
  - images               x86_64     SLES15-SP1-SAP-Azure-VLI-BYOS:Devel building
```

**Comment by schaefi** [comment]
@aosthof please take a look at the resolver list for the packages you added:

```
<bdep name="drbd-formula" noinstall="1" version="0.3.10" release="1.7" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
<bdep name="habootstrap-formula" noinstall="1" version="0.2.10" release="1.7" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
<bdep name="python2-shaptools" noinstall="1" version="0.3.5" release="1.11" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
<bdep name="salt-shaptools" noinstall="1" version="0.2.12" release="1.7" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
<bdep name="saphanabootstrap-formula" noinstall="1" version="0.4.2" release="1.7" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
<bdep name="sapnwbootstrap-formula" noinstall="1" version="0.1.8" release="1.7" arch="noarch" project="SUSE:SLE-15-SP2:GA" repository="standard"/>
```

Is this expected and correct ?

One thing I noted is python2-shaptools. python2 is EOL, I wonder where sle15-sp2 still supports py2 ?

Anyway please double check and give me your ok here on git before I will run the submit request to the SUSE namespace.

Thanks much

**Comment by aosthof** [comment]
Looks good to me, all 6 packages are fetched from SUSE:SLE-15-SP2:GA. That's the place where the SLES for SAP team has put them. Regarding the python2 I'm not sure, but that is what was requested by them.

**Comment by schaefi** [comment]
ok, I will prepare submissions to the SUSE namespace. Thanks

**Pull request merged**
