### PR TITLE
Extend installer service

### LINKED ISSUE #120: Need ability to install a software repository
This is VLI-specific right now, but seems like a useful feature in general.

`SFS` (Software Foundation Services) software is distributed as a repository. Currently, we can install RPMs (which is great for UCS, since their drivers are distributed as .rpm files with no dependencies). But `SFS` is distributed as a repository.

My thought here is that SFS would be in a directory on the configuration LUN (perhaps `/sfsrepo`), and I can point to that from the YAML to process it as a repository.

Here's the rough instructions I have for installing `SFS` today:

- Download the foundation-2.19-cd1-media-sles12sp3-x86_64.iso image file to the server.

- Add System Foundation Software as a new software repository. The following example shows how to configure ISO as a new software repository:

```
# zypper ar -c -t yast2 "iso:/?iso=/var/foundation-2.19.iso" "SFS-2.19"  ß Change the path
Adding repository 'SFS-2.19' ......................................[done]
Repository 'SFS-2.19' successfully added
Enabled: Yes
Autorefresh: No
GPG check: Yes
URI: iso:///?iso=/var/foundation-2.19.iso
```

- Refresh the software repository metadata.

```
#zypper refresh
```

- Install the System Foundation Software pattern

```
#zypper install -t pattern System-Foundation-Software
<Follow any on-screen instructions to complete the installation.>
```

- Reboot the system to complete the installation

It's annoying that SFS requires a reboot to get going - presumably you can combine this one, if needed (make it optional based on YAML), with the "non-post" (quick) reboot for crash dumps.

Doable? For YAML, perhaps something like:

```
packages:
  repository_name: azure_packages
  directory:
    - "rpms/" 
  repository:
    - 
    Directory: "sfsrepo/"
    Pattern: System-Foundation-Software
    -
    Directory: "anotherrepo/"
    Pattern: "Another-Pattern"
    -
  reboot: yes
```

If `reboot` wasn't specified, or if it was specified with something other than `yes` (or `true`?), then the system wouldn't be rebooted just for the repository installation.

Something like this, anyway.

Thoughts or suggestions?

### PR DESCRIPTION
**Pull request by schaefi**
Allow to configure multiple repositories and formats not only
packages from a directory list. Specifically add packages to
install in an install section. This Fixes #120

### CODE REVIEW

**Comment by schaefi** [comment]
This pull request changes the way we define package installation tasks. So in short it looks like this now

```yaml
packages:
  repository:
    -
      name: fsf
      source: /path/to/file.iso
      source_prefix: iso:/?iso=

    -
      name: some_other_repo
      source: /path/to/repo

  raw:
    name: azure_packages
    directory:
      - "directory-with-rpm-files"
      - "another-directory-with-rpm-files"

  install:
    - package_a
    - package_b
```

The install section specifies which packages should be installed. The implementation before this PR installed all packages from the provided directory. However with the ability to add repos like the fsf iso it's required to express what packages should be installed. This is imho also better to explicitly express what should be installed.

So the change impacts the yaml setup for package installations and must be taken into account if this one gets accepted and merged

**Comment by jeffaco** [comment]
I need a little bit of clarification on the new YAML format.

I presume that `install:` list refers to the packages to install from the repository? So, for something like SFS, you'd have something like:

```
packages:
  repository:
    -
      name: sfs
      source: /repo/foundation-2.19.iso
      source_prefix: iso:/?iso=
  install:
    - System-Foundation-Software
```

Is that about right? I'm not quite sure of `source_prefix`, and what that does exactly (other than tell the system that it's an ISO to unpack)?

I presume the `install:` section only relates to repositories, as the `raw:` section installs any `.rpm` files in the stated directories? If we were only specifying the `raw:` section, then I presume it would be illogical (probably invalid) to specify the `install:` section?

**Comment by schaefi** [comment]
> I presume that install: list refers to the packages to install from the repository?

correct. You specify the list of packages you want to install. The zypper install request will take all repos configured on the system into account to fulfill this request

> I'm not quite sure of source_prefix, and what that does exactly (other than tell the system
> that it's an ISO to unpack)?

It does what the name says and prepends the given prefix to the source. It's an optional value but in case of an iso file as source repo it's a must have to tell zypper the repo is an iso. This additional information makes zypper aware that it internally needs to loopback mount the iso before it can access the contents. I did not add any intelligence here because I think the code writing that yaml file knows if the specified source needs a source prefix or not.

> I presume the install: section only relates to repositories, as the raw: section installs any .rpm files in > the stated directories? If we were only specifying the raw: section, then I presume it would be illogical > (probably invalid) to specify the install: section?

Nope that behavior would change now. Formerly the code reads all rpm files it could find in the given directories and created a ```zypper install``` command from it. You wouldn't had any chance to just install one or two packages from the directories and that implicit "magic" did not state what packages will be installed. Now with the additional feature to allow adding full repos like it is provided in the fsf iso file I think that logic should change into an explicit list of packages which should become installed.

I'm aware that it would affect the behavior of the former implementation. Given you specify only a raw section like this:

```yaml
packages:
  raw:
    name: azure_packages
    directory:
      - "directory-with-rpm-files"
      - "another-directory-with-rpm-files"
```

this would only lead to setting up the repo but not packages gets installed. So the information:

```
install:
    - foo
    - bar
```

would now be needed if you want to install packages. Which was not needed before.

If this is unwanted please let me know

However I recommend we go with that change because if you specify both repos plus raw dirs and I take raw dirs content always into account as list of packages to become installed it will result in a weird implicit package install behavior. I think having it explicitly requested makes it totally clear and we should aim for that

Thanks

**Comment by rjschwei** [comment]
I think we should have a keyword in case it is desired to install all packages, either

`Install:
    - all`

or

`Install:
    - *`

**Comment by schaefi** [comment]
How should that work, if in addition to raw directories a repo like the software-foundation iso is attached ? Install all from dirs and the repo, that doesn't make sense to me. And again I very much dislike implicit magic. A repo could come with hundreds of packages, collecting them all and creating one big install instruction is not a good idea. Also repos almost always contains in itself conflicting packages, e.g postfix vs. sendmail. A big instruction set from all available only creates trouble sooner or later.

We shouldn't have done it that way from the beginning on imho

**Comment by rjschwei** [comment]
I think `install` should be by repo. Then for the case where things are put in a directory with a specifically crafted content the "all" keyword can be used without having effect on other more general repos such as a repo from an ISO file. Also have "install" per repo helps the user to correlate the packages to a certain source.

The argument of "hundreds of packages" goes both ways. If one wants to install a hundred or more packages, one would have to generate 100 entries in the YAML file, ugh, why would we make th euser work that hard?

**Comment by schaefi** [comment]
> The argument of "hundreds of packages" goes both ways. If one wants to install a hundred or more
> packages, one would have to generate 100 entries in the YAML file, ugh, why would we make th euser
> work that hard?

This is different. I was talking about installing _everything_ from a repo which can accumulate to a hundred or more packages which is an instruction that doesn't make sense. So applying the same "install all" process on repos doesn't make sense. The only way to differentiate and keep the behavior for directories as it was before is to maintain ```install``` by repo

I can do that

**Comment by jeffaco** [comment]
I think, in the case of SFS, it should work with dependencies (as the instructions from HPE indicate).

You may already have a bunch of software installed from the repo. For example, SFS requires `python` (I think), so it includes `python` in the repo (with relevant dependencies). But our systems always have `python` already, so these should just be ignored as a dependency (assuming version is satisfied, etc).

If I understand your earlier message, I'm not a fan of treating a repository like installing "all" files in the repository. Installations from repositories should manage their dependency, like with any other repository.

But, in case of installation of RPMs, just handle that as in the past. We'll never have 100 RPMs in a directory to install, that's just not our use case. We'd use a repository for that.

There are two use cases here:

1. Cisco ENCI/FNIC drivers. These are two RPM files with no dependencies.
1. SFS software. This is a repository with a fair chunk of packages within it, and has specific instructions from HPE on how to install it.

We should clearly cover our two use cases.

**Comment by schaefi** [comment]
ok all done now. The final schema specification is as follows:

```yaml
packages:
  repository:
    -
      name: fsf
      source: /path/to/file.iso
      source_prefix: iso:/?iso=
      install:
        - package_a

    -
      name: some_repo
      source: /path/to/repo
      install:
        - package_b

  raw:
    name: azure_packages
    directory:
      - "directory-with-rpm-files"
      - "another-directory-with-rpm-files"
```

The above will setup three local repositories ```fsf, some_repo``` and ```azure_packages```
An install request for ```package_a, package_b, [content_of_raw_dirs]``` will be issued taking all configured repos on the system into account (including the ones setup here)

**Comment by schaefi** [comment]
> But, in case of installation of RPMs, just handle that as in the past

yes, done see above

> I think install should be by repo

yes, done see above

**Comment by schaefi** [comment]
@rjschwei weekend work :) we love what we do right ;) my son just wrote his first hello world in python today :-) looking into that network stuff next

**Pull request merged**
